"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { serverClient } from "@/lib/supabase/server";

export type InvitationState = { token?: string; error?: string };
type SportsSyncResponse = { ok: boolean; affected?: number; warning?: string; gamesUpdated?: number; oddsLines?: number };

function text(form: FormData, name: string): string { const value = form.get(name); return typeof value === "string" ? value : ""; }
function fail(error: { message: string } | null): never { redirect(`/?error=${encodeURIComponent(error?.message ?? "Unable to save your change")}`); }

export async function createPool(form: FormData) { const db=await serverClient(); const { error }=await db.rpc("create_pool",{p_name:text(form,"name")}); if(error) fail(error); revalidatePath("/"); redirect("/"); }
export async function submitPick(form: FormData) { const db=await serverClient(); const { error }=await db.rpc("submit_pick",{p_pool_id:text(form,"poolId"),p_week_id:text(form,"weekId"),p_game_id:text(form,"gameId"),p_team_id:text(form,"teamId")}); if(error) redirect(`/pick?error=${encodeURIComponent(error.message)}`); revalidatePath("/"); revalidatePath("/pick"); redirect("/pick?saved=1"); }
export async function submitAssistedPick(form: FormData) { const [gameId,teamId]=text(form,"selection").split("|"); if(!gameId || !teamId) redirect("/admin?error=Choose%20a%20game"); const db=await serverClient(); const { error }=await db.rpc("submit_pick",{p_pool_id:text(form,"poolId"),p_week_id:text(form,"weekId"),p_game_id:gameId,p_team_id:teamId,p_player_id:text(form,"playerId")}); if(error) redirect(`/admin?error=${encodeURIComponent(error.message)}`); revalidatePath("/"); revalidatePath("/pick"); revalidatePath("/admin"); redirect("/admin?assisted=1"); }
export async function moderateMember(form: FormData) { const db=await serverClient(); const {error}=await db.rpc("moderate_membership",{p_pool_id:text(form,"poolId"),p_user_id:text(form,"userId"),p_status:text(form,"status")}); if(error) fail(error); revalidatePath("/admin"); }
export async function changeMemberRole(form: FormData) { const db=await serverClient(); const {error}=await db.rpc("set_pool_member_role",{p_pool_id:text(form,"poolId"),p_user_id:text(form,"userId"),p_role:text(form,"role")}); if(error) fail(error); revalidatePath("/admin"); }
export async function redeemInvitation(form: FormData) { const token=text(form,"token"); const db=await serverClient(); const {error}=await db.rpc("request_pool_membership",{p_token:token}); if(error) redirect(`/join?token=${encodeURIComponent(token)}&error=${encodeURIComponent(error.message)}`); redirect("/?requested=1"); }
export async function createInvitation(_: InvitationState, form: FormData): Promise<InvitationState> { const db=await serverClient(); const {data,error}=await db.rpc("create_invitation",{p_pool_id:text(form,"poolId")}); if(error) return {error:error.message}; const row=(data as unknown as Array<{token:string}> | null)?.[0]; if(!row) return {error:"Unable to create invitation"}; revalidatePath("/admin"); return {token:row.token}; }
function importResultPath(data: SportsSyncResponse): string { const params = new URLSearchParams({ imported: String(data.affected ?? 0), gamesUpdated: String(data.gamesUpdated ?? 0), oddsLines: String(data.oddsLines ?? 0) }); if(data.warning) params.set("syncWarning",data.warning); return `/admin?${params}`; }
export async function openWeek(form: FormData) { const db=await serverClient(); const poolId=text(form,"poolId"), week=Number(text(form,"week")); const {error}=await db.rpc("create_pool_week",{p_pool_id:poolId,p_week:week}); if(error) redirect(`/admin?error=${encodeURIComponent(error.message)}`); const { data: { session } }=await db.auth.getSession(); const {data,error:syncError}=await db.functions.invoke<SportsSyncResponse>("sports-sync",{body:{source:"commissioner-open-week",poolId,week},headers:session ? {Authorization:`Bearer ${session.access_token}`} : {}}); if(syncError || !data?.ok) redirect(`/admin?error=${encodeURIComponent(syncError?.message ?? "Schedule import failed. Check the NFL data setup and function logs.")}`); revalidatePath("/"); revalidatePath("/admin"); redirect(importResultPath(data)); }
export async function importSchedule(form: FormData) { const db=await serverClient(); const poolId=text(form,"poolId"), week=Number(text(form,"week")); const { data: { session } }=await db.auth.getSession(); const {data,error}=await db.functions.invoke<SportsSyncResponse>("sports-sync",{body:{source:"commissioner-manual-import",poolId,week},headers:session ? {Authorization:`Bearer ${session.access_token}`} : {}}); if(error || !data?.ok) redirect(`/admin?error=${encodeURIComponent(error?.message ?? "Schedule import failed. Check the NFL data setup and function logs.")}`); revalidatePath("/"); revalidatePath("/admin"); redirect(importResultPath(data)); }
export async function resetPool(form: FormData) { if(text(form,"confirmation") !== "RESET") redirect("/admin?error=Reset+confirmation+did+not+match"); const db=await serverClient(); const {error}=await db.rpc("reset_pool",{p_pool_id:text(form,"poolId")}); if(error) redirect(`/admin?error=${encodeURIComponent(error.message)}`); revalidatePath("/"); revalidatePath("/admin"); revalidatePath("/pick"); revalidatePath("/picks"); revalidatePath("/standings"); redirect("/admin?reset=1"); }
export async function saveManualLine(form: FormData) { const db=await serverClient(); const kickoff=text(form,"kickoff"); const {error}=await db.rpc("upsert_manual_line",{p_pool_id:text(form,"poolId"),p_week_id:text(form,"weekId"),p_away_abbreviation:text(form,"away"),p_home_abbreviation:text(form,"home"),p_kickoff:new Date(kickoff).toISOString(),p_underdog_abbreviation:text(form,"underdog"),p_spread:Number(text(form,"spread"))}); if(error) redirect(`/admin?error=${encodeURIComponent(error.message)}`); revalidatePath("/"); revalidatePath("/pick"); revalidatePath("/admin"); redirect("/admin"); }
export async function saveScheduledLine(form: FormData) { const db=await serverClient(); const {error}=await db.rpc("upsert_scheduled_line",{p_pool_id:text(form,"poolId"),p_week_id:text(form,"weekId"),p_game_id:text(form,"gameId"),p_underdog_team_id:text(form,"underdogTeamId"),p_spread:Number(text(form,"spread"))}); if(error) redirect(`/admin?error=${encodeURIComponent(error.message)}`); revalidatePath("/"); revalidatePath("/pick"); revalidatePath("/admin"); redirect("/admin"); }
export async function recordManualResult(form: FormData) { const db=await serverClient(); const {error}=await db.rpc("record_manual_game_result",{p_pool_id:text(form,"poolId"),p_game_id:text(form,"gameId"),p_home_score:Number(text(form,"homeScore")),p_away_score:Number(text(form,"awayScore"))}); if(error) redirect(`/admin?error=${encodeURIComponent(error.message)}`); revalidatePath("/"); revalidatePath("/picks"); revalidatePath("/standings"); revalidatePath("/admin"); redirect("/admin"); }
export async function finalizeWeek(form: FormData) { const db=await serverClient(); const {error}=await db.rpc("finalize_pool_week",{p_pool_id:text(form,"poolId"),p_week_id:text(form,"weekId")}); if(error) redirect(`/admin?error=${encodeURIComponent(error.message)}`); revalidatePath("/"); revalidatePath("/picks"); revalidatePath("/standings"); revalidatePath("/admin"); redirect("/admin?finalized=1"); }
