import Link from "next/link";
import { CircleAlert, MessageCircle, RotateCcw } from "lucide-react";
import { Header, BottomNav } from "@/components/navigation";
import { PickFlow } from "@/components/pick-flow";
import { Onboarding } from "@/components/onboarding";
import { Button, Card } from "@/components/ui";
import { resumePoolWeek, skipPoolWeek } from "@/app/actions/pool";
import { requirePoolContext } from "@/lib/data/pool";

type PickParams = { saved?: string; error?: string; resumed?: string; skipped?: string; week?: string; seasonType?: "preseason" | "regular" | "postseason"; pool?: string };

export default async function PickPage({ searchParams }: { searchParams: Promise<PickParams> }) {
  const params = await searchParams;
  const selectedWeek = Number(params.week);
  const context = await requirePoolContext(Number.isInteger(selectedWeek) ? selectedWeek : undefined, params.seasonType, params.pool);
  if (!context.pool || !context.week) return <main className="min-h-screen"><Header weekNumber={context.week?.nfl_week} weeks={context.weeks} pools={context.pools} pool={context.pool}/><Onboarding pending={context.pendingPool}/><BottomNav/></main>;
  if (context.pickBlocked) return <main className="mx-auto min-h-screen max-w-5xl pb-24"><Header weekNumber={context.week.nfl_week} weeks={context.weeks} pools={context.pools} pool={context.pool}/><section className="mx-auto grid min-h-[65vh] max-w-xl place-items-center px-5 py-10"><Card className="w-full border-amber-400/35 bg-[hsl(var(--elevated))] p-7 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-amber-400/15 text-amber-200"><CircleAlert size={28}/></span><p className="eyebrow mt-5 text-amber-200">Pick access paused</p><h1 className="mt-2 text-3xl font-black">Contact the commissioner.</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-[hsl(var(--muted))]">Your pick access is temporarily paused. Please contact the commissioner to restore access before making a selection.</p><Link className="mt-6 inline-flex" href={`/?pool=${context.pool.id}`}><Button><MessageCircle className="mr-2" size={16}/>Return to home</Button></Link></Card></section><BottomNav/></main>;
  if (context.weekSkipped) return <main className="mx-auto min-h-screen max-w-5xl pb-24"><Header weekNumber={context.week.nfl_week} weeks={context.weeks} pools={context.pools} pool={context.pool}/><section className="mx-auto grid min-h-[65vh] max-w-xl place-items-center px-5 py-10"><Card className="w-full p-7 text-center"><p className="eyebrow">Week {context.week.nfl_week}</p><h1 className="mt-2 text-3xl font-black">You&apos;re sitting this one out.</h1><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-[hsl(var(--muted))]">You won&apos;t be able to make a pick for this week. You&apos;ll automatically be ready for the next week, or you can return to this one while it&apos;s still open.</p><form action={resumePoolWeek} className="mt-6"><input type="hidden" name="poolId" value={context.pool.id}/><input type="hidden" name="weekId" value={context.week.id}/><input type="hidden" name="week" value={context.week.nfl_week}/><Button type="submit"><RotateCcw className="mr-2" size={16}/>Return to Week {context.week.nfl_week}</Button></form></Card></section><BottomNav/></main>;
  const currentPick = context.picks.find((pick) => pick.playerId === context.userId && context.games.some((game) => game.id === pick.gameId));
  return <main className="mx-auto min-h-screen max-w-5xl pb-24"><Header weekNumber={context.week.nfl_week} weeks={context.weeks} pools={context.pools} pool={context.pool}/>{params.resumed && <p className="mx-5 mt-2 rounded-xl bg-[hsl(var(--primary)/.12)] p-3 text-sm font-bold text-[hsl(var(--primary))]">You&apos;re back in for Week {context.week.nfl_week}.</p>}<PickFlow poolId={context.pool.id} weekId={context.week.id} weekNumber={context.week.nfl_week} weekWindow={context.weekWindow} games={context.games} currentPick={currentPick} saved={params.saved === "1"} error={params.error}/><section className="px-5 pb-4"><Card className="border-white/10 bg-white/[.025] p-4"><p className="font-black">Not playing this week?</p><p className="mt-1 text-sm text-[hsl(var(--muted))]">Skip Week {context.week.nfl_week} and you&apos;ll automatically return for the next week. Any unlocked pick for this week will be removed.</p><form action={skipPoolWeek} className="mt-4"><input type="hidden" name="poolId" value={context.pool.id}/><input type="hidden" name="weekId" value={context.week.id}/><input type="hidden" name="week" value={context.week.nfl_week}/><Button type="submit" className="bg-white/10 text-white hover:bg-white/15">I don&apos;t want to pick this week</Button></form></Card></section><BottomNav/></main>;
}
