import Link from "next/link";
import { Activity, CalendarDays, ChevronDown, ClipboardCheck, ListChecks, Settings2, Users, UserPlus, UsersRound } from "lucide-react";
import type { ReactNode } from "react";
import { changeMemberRole, finalizeWeek, importSchedule, moderateMember, openWeek, recordManualResult, saveManualLine, saveMemberNote, saveScheduledLine, setMemberPickBlock, submitAssistedPick } from "@/app/actions/pool";
import { InvitationForm } from "@/components/invitation-form";
import { CommissionerSetupWizard } from "@/components/commissioner-setup-wizard";
import { BottomNav, Header } from "@/components/navigation";
import { Onboarding } from "@/components/onboarding";
import { ResetPoolForm } from "@/components/reset-pool-form";
import { Button, Card, Pill } from "@/components/ui";
import { requirePoolContext, type LiveGame, type PoolMember, type ScheduledGame } from "@/lib/data/pool";
import { formatEastern } from "@/lib/domain/deadlines";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ assisted?: string; error?: string; finalized?: string; imported?: string; memberBlock?: string; memberNote?: string; reset?: string; gamesUpdated?: string; oddsLines?: string; syncWarning?: string; setup?: string; week?: string }> }) {
  const params = await searchParams;
  const selectedWeek = Number(params.week);
  const context = await requirePoolContext(Number.isInteger(selectedWeek) ? selectedWeek : undefined);
  const pool = context.pool;
  if (!pool) return <main className="min-h-screen"><Header weekNumber={context.week?.nfl_week} weeks={context.weeks}/><Onboarding pending={context.pendingPool}/><BottomNav/></main>;
  if (pool.role !== "commissioner" && pool.role !== "co_commissioner") return <main className="min-h-screen"><Header weekNumber={context.week?.nfl_week} weeks={context.weeks}/><section className="mx-auto max-w-xl px-5 pt-16"><h1 className="text-3xl font-black">Commissioner access required</h1></section><BottomNav/></main>;

  const active = context.members.filter((member) => member.status === "active");
  const pending = context.members.filter((member) => member.status === "pending");
  const setupIncomplete = !context.week || !context.schedule.length || context.schedule.some((game) => !game.hasLine);
  const stats = [[String(active.length), "Active players", Users], [String(context.picks.length), "Picks submitted", ClipboardCheck], [String(pending.length), "Pending members", UserPlus], [context.lastSync ? "Live" : "Waiting", "NFL data", Activity]];

  return <main className="mx-auto min-h-screen max-w-5xl pb-24"><Header weekNumber={context.week?.nfl_week} weeks={context.weeks}/><section className="px-5 pt-6">
    <Pill className="border-[hsl(var(--primary)/.4)] text-[hsl(var(--primary))]">Commissioner area</Pill>
    <div className="mt-3 flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-black">Run Week {context.week?.nfl_week ?? "—"}</h1>{!setupIncomplete && <Link className="inline-flex" href={`/admin?setup=1&week=${context.week?.nfl_week ?? ""}`}><Button className="bg-white/10 text-white hover:bg-white/15">Open setup guide</Button></Link>}</div>
    {params.error && <Card className="mt-5 border-red-500/40 p-4 text-sm text-red-200">{params.error}</Card>}
    {params.imported !== undefined && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Official schedule refreshed: {params.gamesUpdated ?? "0"} game{params.gamesUpdated === "1" ? "" : "s"} imported or updated; {params.oddsLines ?? "0"} provider line{params.oddsLines === "1" ? "" : "s"} prefilled.</Card>}
    {params.syncWarning && <Card className="mt-5 border-amber-400/40 p-4 text-sm text-amber-100">Odds were not fully prefilled: {params.syncWarning} Add any missing line manually, then check the latest <code>provider_syncs</code> row.</Card>}
    {params.assisted && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Assisted pick saved and recorded in the audit trail.</Card>}
    {params.memberBlock && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">{params.memberBlock === "paused" ? "Pick access paused. The member will see a contact-the-commissioner message." : "Pick access restored for the member."}</Card>}
    {params.memberNote && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Private member note saved.</Card>}
    {params.finalized && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Week finalized. Season standings now include every official result.</Card>}
    {params.reset && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Pool reset. Members were retained; open a new week to start again.</Card>}
    <div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-4">{stats.map(([value, label, Icon]) => { const Symbol = Icon as typeof Users; return <Card className="p-4" key={label as string}><Symbol className="text-[hsl(var(--primary))]" size={18}/><p className="mt-5 text-2xl font-black">{value as string}</p><p className="text-xs font-bold text-[hsl(var(--muted))]">{label as string}</p></Card>; })}</div>
    {(setupIncomplete || params.setup === "1") && <CommissionerSetupWizard activeMembers={active.length} poolId={pool.id} role={pool.role === "commissioner" ? "commissioner" : "co_commissioner"} schedule={context.schedule} week={context.week}/>}
    <CommissionerSection title="Pool setup" description="Invitations and data connection" icon={Settings2}>
      <div className="grid gap-4 md:grid-cols-2"><InvitationForm poolId={pool.id}/><Card className="p-5"><p className="eyebrow">NFL data</p><p className="mt-2 text-xl font-black text-[hsl(var(--primary))]">{context.lastSync ? "Connected" : "Awaiting sync"}</p><p className="mt-2 text-sm text-[hsl(var(--muted))]">{context.lastSync ? `Last successful sync: ${new Date(context.lastSync).toLocaleString()}` : "Deploy and schedule the Supabase sports-sync function."}</p></Card></div>
    </CommissionerSection>
    <WeekAndLineTools poolId={pool.id} week={context.week} schedule={context.schedule}/><AssistedPickForm poolId={pool.id} weekId={context.week?.id} members={active} games={context.games}/><ResultsTools poolId={pool.id} week={context.week} games={context.games}/><MemberList poolId={pool.id} commissioner={pool.role === "commissioner"} currentUserId={context.userId} members={context.members} notes={context.memberNotes}/>{pool.role === "commissioner" && <CommissionerSection title="Pool reset" description="Remove gameplay data while retaining members" icon={Settings2}><ResetPoolForm poolId={pool.id}/></CommissionerSection>}
  </section><BottomNav/></main>;
}

function CommissionerSection({ title, description, icon: Icon, open = false, children }: { title: string; description: string; icon: typeof CalendarDays; open?: boolean; children: ReactNode }) {
  return <details className="group surface mt-4 overflow-hidden rounded-2xl" open={open}>
    <summary className="focus-ring flex min-h-16 cursor-pointer list-none items-center gap-3 px-5 py-4 marker:content-none">
      <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[hsl(var(--primary)/.12)] text-[hsl(var(--primary))]"><Icon size={19}/></span>
      <span className="min-w-0 flex-1"><span className="block font-black">{title}</span><span className="mt-0.5 block truncate text-xs text-[hsl(var(--muted))]">{description}</span></span>
      <ChevronDown className="shrink-0 text-[hsl(var(--muted))] transition group-open:rotate-180" size={18}/>
    </summary>
    <div className="border-t border-white/10 px-4 pb-5 pt-4 sm:px-5">{children}</div>
  </details>;
}

function WeekAndLineTools({ poolId, week, schedule }: { poolId: string; week: { id: string; nfl_week: number; status: "draft" | "open" | "complete" } | null; schedule: ScheduledGame[] }) {
  return <CommissionerSection title="Calendar & game lines" description={week ? `Prepare and manage Week ${week.nfl_week}` : "Set up your first week"} icon={CalendarDays} open={!week || schedule.some((game) => !game.hasLine)}><div>
    {!week ? <form action={openWeek} className="mt-4 flex flex-wrap gap-3"><input type="hidden" name="poolId" value={poolId}/><input className="focus-ring min-h-11 w-28 rounded-xl border bg-black/20 px-3 text-sm" name="week" type="number" min="1" max="25" required placeholder="Week"/><Button type="submit">Set up & import week</Button></form>
      : <><p className="mt-4 text-sm text-[hsl(var(--primary))]">Set up future weeks whenever you&apos;re ready. Every active pool member carries over automatically.</p><form action={openWeek} className="mt-4 flex flex-wrap gap-3"><input type="hidden" name="poolId" value={poolId}/><input className="focus-ring min-h-11 w-28 rounded-xl border bg-black/20 px-3 text-sm" name="week" type="number" min="1" max="25" required defaultValue={week.nfl_week + 1}/><Button type="submit">Set up another week</Button></form>{week.status === "complete" ? <p className="mt-5 text-sm text-[hsl(var(--muted))]">Week {week.nfl_week} is final. Select another week above to manage its schedule and lines.</p> : <><div className="mt-5 flex flex-wrap items-center gap-3"><form action={importSchedule}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="week" value={week.nfl_week}/><Button type="submit">Import / refresh official schedule</Button></form><p className="text-xs text-[hsl(var(--muted))]">Fetches the latest NFL schedule, scores, and available odds for Week {week.nfl_week}.</p></div>{schedule.length ? <><p className="mt-5 text-sm text-[hsl(var(--muted))]">Provider lines are prefilled only when a usable spread is returned. Blank fields need a commissioner line; they are never guessed.</p><div className="mt-4 grid gap-3">{schedule.map((game) => <ScheduledLineForm key={game.id} poolId={poolId} weekId={week.id} game={game}/>)}</div></> : <ManualLineForm poolId={poolId} weekId={week.id}/>}</>}</>}
    {!week && <p className="mt-3 text-xs text-[hsl(var(--muted))]">Opening a week imports the official NFL schedule immediately. The background sync keeps scores and kickoff times current.</p>}
    {week && week.status !== "complete" && !schedule.length && <p className="mt-3 text-xs text-[hsl(var(--muted))]">The schedule is still loading or the provider is unavailable. You can add a manual game line as a fallback; it will be preserved from provider updates.</p>}
  </div></CommissionerSection>;
}

function ScheduledLineForm({ poolId, weekId, game }: { poolId: string; weekId: string; game: ScheduledGame }) {
  const source = game.lineSource?.replace("balldontlie:", "BALLDONTLIE · ").replace("therundown:", "TheRundown · ");
  return <details className="group rounded-xl border border-white/10 bg-black/10" open={!game.hasLine}><summary className="focus-ring flex min-h-14 cursor-pointer list-none items-center gap-3 px-3 marker:content-none"><span className="min-w-0 flex-1"><span className="block truncate font-bold">{game.away.name} at {game.home.name}</span><span className="mt-0.5 block truncate text-xs text-[hsl(var(--muted))]">{formatEastern(game.kickoff)}{source ? ` · ${game.lineManuallyOverridden ? "Edited" : source}` : ""}</span></span><Pill className={game.hasLine ? "border-[hsl(var(--primary)/.35)] text-[hsl(var(--primary))]" : "border-amber-400/35 text-amber-200"}>{game.hasLine ? "Line ready" : "Needs line"}</Pill><ChevronDown className="shrink-0 text-[hsl(var(--muted))] transition group-open:rotate-180" size={16}/></summary><form action={saveScheduledLine} className="grid gap-3 border-t border-white/10 p-3 md:grid-cols-[minmax(0,1fr)_11rem_8rem_auto]"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={weekId}/><input type="hidden" name="gameId" value={game.id}/><p className="hidden md:block"/><select name="underdogTeamId" defaultValue={game.underdogTeamId ?? ""} required className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm"><option value="" disabled>Choose underdog</option><option value={game.away.id}>{game.away.abbreviation} — {game.away.name}</option><option value={game.home.id}>{game.home.abbreviation} — {game.home.name}</option></select><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="spread" defaultValue={game.spread ?? undefined} required type="number" min="0.5" step="0.5" placeholder="Spread"/><Button type="submit" className={game.hasLine ? "bg-white/10 text-white" : undefined}>{game.hasLine ? "Save edit" : "Add line"}</Button></form></details>;
}

function ManualLineForm({ poolId, weekId }: { poolId: string; weekId: string }) { return <form action={saveManualLine} className="mt-4 grid gap-3 md:grid-cols-5"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={weekId}/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="away" required maxLength={3} placeholder="Away (NYJ)"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="home" required maxLength={3} placeholder="Home (BUF)"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="underdog" required maxLength={3} placeholder="Underdog"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="spread" required type="number" min="0.5" step="0.5" placeholder="Spread"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm md:col-span-2" name="kickoff" required type="datetime-local"/><Button type="submit">Add game line</Button></form>; }

function AssistedPickForm({ poolId, weekId, members, games }: { poolId: string; weekId: string | undefined; members: PoolMember[]; games: LiveGame[] }) { const options=games.filter((game)=>game.available); return <CommissionerSection title="Player picks" description="Add or update a pick on a player&apos;s behalf" icon={ListChecks}>{weekId && options.length ? <form action={submitAssistedPick} className="grid gap-3 md:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)_auto]"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={weekId}/><select name="playerId" required className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm"><option value="" disabled>Select player</option>{members.map((member)=><option key={member.userId} value={member.userId}>{member.displayName}</option>)}</select><select name="selection" required className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm"><option value="" disabled>Select underdog</option>{options.map((game)=><option key={game.id} value={`${game.id}|${game.underdog.id}`}>{game.underdog.abbreviation} +{game.spread} vs {game.favorite.abbreviation} · {formatEastern(game.kickoff)}</option>)}</select><Button type="submit">Save player pick</Button></form> : <p className="text-sm text-[hsl(var(--muted))]">No currently eligible games are available for a player pick.</p>}</CommissionerSection>; }

function ResultsTools({ poolId, week, games }: { poolId: string; week: { id: string; nfl_week: number; status: "draft" | "open" | "complete" } | null; games: LiveGame[] }) { if(!week) return null; return <CommissionerSection title="Results & week close" description="Scores, corrections, and finalization" icon={ClipboardCheck}><p className="text-sm text-[hsl(var(--muted))]">Provider-scored games finalize automatically. Use a manual score only for a correction or a manually entered fallback game.</p><div className="mt-4 grid gap-3">{games.filter((game)=>game.status!=="final").map((game)=><form key={game.id} action={recordManualResult} className="grid items-center gap-3 rounded-xl border border-white/10 bg-black/10 p-3 md:grid-cols-[minmax(0,1fr)_6rem_6rem_auto]"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="gameId" value={game.id}/><p className="font-bold">{game.away.abbreviation} at {game.home.abbreviation}</p><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="awayScore" required min="0" type="number" placeholder={`${game.away.abbreviation}`}/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="homeScore" required min="0" type="number" placeholder={`${game.home.abbreviation}`}/><Button type="submit" className="bg-white/10 text-white">Record result</Button></form>)}</div>{week.status !== "complete" ? <form action={finalizeWeek} className="mt-5"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={week.id}/><Button type="submit">Finalize Week {week.nfl_week}</Button></form> : <p className="mt-5 text-sm font-bold text-[hsl(var(--primary))]">Week {week.nfl_week} is finalized.</p>}</CommissionerSection>; }

function MemberList({ poolId, commissioner, currentUserId, members, notes }: { poolId: string; commissioner: boolean; currentUserId: string; members: PoolMember[]; notes: Record<string, string> }) {
  return <CommissionerSection title="Members" description={`${members.filter((member) => member.status === "active").length} active · ${members.filter((member) => member.status === "pending").length} pending`} icon={UsersRound}>
    {commissioner && <p className="border-b border-white/10 px-4 py-3 text-xs text-[hsl(var(--muted))]">Member notes are visible only to you.</p>}
    {members.map((member) => <div className="border-b border-white/5 p-4 last:border-0" key={member.userId}>
      <div className="flex flex-wrap items-center gap-3">
        <div className="min-w-36 flex-1"><p className="font-bold">{member.displayName}</p><p className="text-xs text-[hsl(var(--muted))]">{member.status} · {member.role.replace("_", " ")}{member.pickBlocked ? <Pill className="ml-2 border-amber-400/40 text-amber-200">Picks paused</Pill> : null}</p></div>
        {member.status === "pending" && commissioner && <><form action={moderateMember}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="userId" value={member.userId}/><input type="hidden" name="status" value="active"/><Button type="submit">Approve</Button></form><form action={moderateMember}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="userId" value={member.userId}/><input type="hidden" name="status" value="rejected"/><Button type="submit" className="bg-white/10 text-white">Reject</Button></form></>}
        {member.status === "active" && member.userId !== currentUserId && commissioner && <form action={changeMemberRole}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="userId" value={member.userId}/><input type="hidden" name="role" value={member.role === "co_commissioner" ? "player" : "co_commissioner"}/><Button type="submit" className="bg-white/10 text-white">{member.role === "co_commissioner" ? "Remove co-commissioner" : "Make co-commissioner"}</Button></form>}
        {member.status === "active" && member.userId !== currentUserId && commissioner && <form action={setMemberPickBlock}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="memberId" value={member.userId}/><input type="hidden" name="blocked" value={member.pickBlocked ? "false" : "true"}/><Button type="submit" className={member.pickBlocked ? "bg-white/10 text-white" : "bg-amber-400 text-amber-950 hover:brightness-110"}>{member.pickBlocked ? "Clear pick block" : "Pause picks & notify"}</Button></form>}
      </div>
      {commissioner && <details className="mt-3 rounded-xl bg-black/15 px-3 py-2"><summary className="focus-ring cursor-pointer text-xs font-bold text-[hsl(var(--primary))]">Private member note{notes[member.userId] ? " · saved" : ""}</summary><form action={saveMemberNote} className="mt-3 grid gap-3"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="memberId" value={member.userId}/><label className="sr-only" htmlFor={`member-note-${member.userId}`}>Note for {member.displayName}</label><textarea className="focus-ring min-h-24 resize-y rounded-xl border bg-black/20 p-3 text-sm" defaultValue={notes[member.userId] ?? ""} id={`member-note-${member.userId}`} maxLength={2000} name="note" placeholder="Add a private note…"/><div className="flex items-center justify-between gap-3"><span className="text-xs text-[hsl(var(--muted))]">Visible only to the commissioner</span><Button type="submit">Save note</Button></div></form></details>}
    </div>)}
  </CommissionerSection>;
}
