import { Activity, ClipboardCheck, Users, UserPlus } from "lucide-react";
import { changeMemberRole, importSchedule, moderateMember, openWeek, saveManualLine, saveScheduledLine } from "@/app/actions/pool";
import { InvitationForm } from "@/components/invitation-form";
import { BottomNav, Header } from "@/components/navigation";
import { Onboarding } from "@/components/onboarding";
import { Button, Card, Pill } from "@/components/ui";
import { requirePoolContext, type ScheduledGame } from "@/lib/data/pool";
import { formatEastern } from "@/lib/domain/deadlines";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ error?: string; imported?: string }> }) {
  const params = await searchParams;
  const context = await requirePoolContext();
  const pool = context.pool;
  if (!pool) return <main className="min-h-screen"><Header weekNumber={context.week?.nfl_week}/><Onboarding pending={context.pendingPool}/><BottomNav/></main>;
  if (pool.role !== "commissioner" && pool.role !== "co_commissioner") return <main className="min-h-screen"><Header weekNumber={context.week?.nfl_week}/><section className="mx-auto max-w-xl px-5 pt-16"><h1 className="text-3xl font-black">Commissioner access required</h1></section><BottomNav/></main>;

  const active = context.members.filter((member) => member.status === "active");
  const pending = context.members.filter((member) => member.status === "pending");
  const stats = [[String(active.length), "Active players", Users], [String(context.picks.length), "Picks submitted", ClipboardCheck], [String(pending.length), "Pending members", UserPlus], [context.lastSync ? "Live" : "Waiting", "NFL data", Activity]];

  return <main className="mx-auto min-h-screen max-w-5xl pb-24"><Header weekNumber={context.week?.nfl_week}/><section className="px-5 pt-6">
    <Pill className="border-[hsl(var(--primary)/.4)] text-[hsl(var(--primary))]">Commissioner area</Pill>
    <h1 className="mt-3 text-3xl font-black">Run Week {context.week?.nfl_week ?? "—"}</h1>
    {params.error && <Card className="mt-5 border-red-500/40 p-4 text-sm text-red-200">{params.error}</Card>}
    {params.imported !== undefined && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Official NFL schedule refreshed: {params.imported} game{params.imported === "1" ? "" : "s"} updated.</Card>}
    <div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-4">{stats.map(([value, label, Icon]) => { const Symbol = Icon as typeof Users; return <Card className="p-4" key={label as string}><Symbol className="text-[hsl(var(--primary))]" size={18}/><p className="mt-5 text-2xl font-black">{value as string}</p><p className="text-xs font-bold text-[hsl(var(--muted))]">{label as string}</p></Card>; })}</div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><InvitationForm poolId={pool.id}/><Card className="p-5"><p className="eyebrow">NFL data</p><p className="mt-2 text-xl font-black text-[hsl(var(--primary))]">{context.lastSync ? "Connected" : "Awaiting sync"}</p><p className="mt-2 text-sm text-[hsl(var(--muted))]">{context.lastSync ? `Last successful sync: ${new Date(context.lastSync).toLocaleString()}` : "Deploy and schedule the Supabase sports-sync function."}</p></Card></div>
    <WeekAndLineTools poolId={pool.id} week={context.week} schedule={context.schedule}/><MemberList poolId={pool.id} commissioner={pool.role === "commissioner"} currentUserId={context.userId} members={context.members}/>
  </section><BottomNav/></main>;
}

function WeekAndLineTools({ poolId, week, schedule }: { poolId: string; week: { id: string; nfl_week: number } | null; schedule: ScheduledGame[] }) {
  return <Card className="mt-6 p-5"><h2 className="font-black">Weeks & lines</h2>
    {!week ? <form action={openWeek} className="mt-4 flex flex-wrap gap-3"><input type="hidden" name="poolId" value={poolId}/><input className="focus-ring min-h-11 w-28 rounded-xl border bg-black/20 px-3 text-sm" name="week" type="number" min="1" max="25" required placeholder="Week"/><Button type="submit">Open & import schedule</Button></form>
      : <><div className="mt-4 flex flex-wrap items-center gap-3"><form action={importSchedule}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="week" value={week.nfl_week}/><Button type="submit">Import / refresh official schedule</Button></form><p className="text-xs text-[hsl(var(--muted))]">Fetches the latest NFL schedule and scores for Week {week.nfl_week}.</p></div>{schedule.length ? <><p className="mt-5 text-sm text-[hsl(var(--muted))]">Week {week.nfl_week} imported. Set just the underdog and spread for each matchup.</p><div className="mt-4 grid gap-3">{schedule.map((game) => <ScheduledLineForm key={game.id} poolId={poolId} weekId={week.id} game={game}/>)}</div></> : <ManualLineForm poolId={poolId} weekId={week.id}/>}</>}
    {!week && <p className="mt-3 text-xs text-[hsl(var(--muted))]">Opening a week imports the official NFL schedule immediately. The background sync keeps scores and kickoff times current.</p>}
    {week && !schedule.length && <p className="mt-3 text-xs text-[hsl(var(--muted))]">The schedule is still loading or the provider is unavailable. You can add a manual game line as a fallback; it will be preserved from provider updates.</p>}
  </Card>;
}

function ScheduledLineForm({ poolId, weekId, game }: { poolId: string; weekId: string; game: ScheduledGame }) {
  return <form action={saveScheduledLine} className="grid items-center gap-3 rounded-xl border border-white/10 bg-black/10 p-3 md:grid-cols-[minmax(0,1fr)_11rem_8rem_auto]"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={weekId}/><input type="hidden" name="gameId" value={game.id}/><div><p className="font-bold">{game.away.name} at {game.home.name}</p><p className="text-xs text-[hsl(var(--muted))]">{formatEastern(game.kickoff)}</p></div><select name="underdogTeamId" defaultValue={game.underdogTeamId ?? ""} required className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm"><option value="" disabled>Choose underdog</option><option value={game.away.id}>{game.away.abbreviation} — {game.away.name}</option><option value={game.home.id}>{game.home.abbreviation} — {game.home.name}</option></select><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="spread" defaultValue={game.spread ?? undefined} required type="number" min="0.5" step="0.5" placeholder="Spread"/><Button type="submit" className={game.hasLine ? "bg-white/10 text-white" : undefined}>{game.hasLine ? "Update line" : "Add line"}</Button></form>;
}

function ManualLineForm({ poolId, weekId }: { poolId: string; weekId: string }) { return <form action={saveManualLine} className="mt-4 grid gap-3 md:grid-cols-5"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={weekId}/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="away" required maxLength={3} placeholder="Away (NYJ)"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="home" required maxLength={3} placeholder="Home (BUF)"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="underdog" required maxLength={3} placeholder="Underdog"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="spread" required type="number" min="0.5" step="0.5" placeholder="Spread"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm md:col-span-2" name="kickoff" required type="datetime-local"/><Button type="submit">Add game line</Button></form>; }

function MemberList({ poolId, commissioner, currentUserId, members }: { poolId: string; commissioner: boolean; currentUserId: string; members: Array<{ userId: string; displayName: string; status: string; role: "player" | "co_commissioner" | "commissioner" }> }) { return <Card className="mt-6 overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="font-black">Members</h2></div>{members.map((member) => <div className="flex flex-wrap items-center gap-3 border-b border-white/5 p-4 last:border-0" key={member.userId}><div className="min-w-36 flex-1"><p className="font-bold">{member.displayName}</p><p className="text-xs text-[hsl(var(--muted))]">{member.status} · {member.role.replace("_", " ")}</p></div>{member.status === "pending" && commissioner && <><form action={moderateMember}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="userId" value={member.userId}/><input type="hidden" name="status" value="active"/><Button type="submit">Approve</Button></form><form action={moderateMember}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="userId" value={member.userId}/><input type="hidden" name="status" value="rejected"/><Button type="submit" className="bg-white/10 text-white">Reject</Button></form></>}{member.status === "active" && member.userId !== currentUserId && commissioner && <form action={changeMemberRole}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="userId" value={member.userId}/><input type="hidden" name="role" value={member.role === "co_commissioner" ? "player" : "co_commissioner"}/><Button type="submit" className="bg-white/10 text-white">{member.role === "co_commissioner" ? "Remove co-commissioner" : "Make co-commissioner"}</Button></form>}</div>)}</Card>; }
