import { Activity, ClipboardCheck, Users, UserPlus } from "lucide-react";
import { changeMemberRole, finalizeWeek, importSchedule, moderateMember, openWeek, recordManualResult, saveManualLine, saveScheduledLine, submitAssistedPick } from "@/app/actions/pool";
import { InvitationForm } from "@/components/invitation-form";
import { BottomNav, Header } from "@/components/navigation";
import { Onboarding } from "@/components/onboarding";
import { ResetPoolForm } from "@/components/reset-pool-form";
import { Button, Card, Pill } from "@/components/ui";
import { requirePoolContext, type LiveGame, type PoolMember, type ScheduledGame } from "@/lib/data/pool";
import { formatEastern } from "@/lib/domain/deadlines";

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ assisted?: string; error?: string; finalized?: string; imported?: string; reset?: string; gamesUpdated?: string; oddsLines?: string; syncWarning?: string }> }) {
  const params = await searchParams;
  const context = await requirePoolContext();
  const pool = context.pool;
  if (!pool) return <main className="min-h-screen"><Header weekNumber={context.week?.nfl_week}/><Onboarding pending={context.pendingPool}/><BottomNav/></main>;
  if (pool.role !== "commissioner" && pool.role !== "co_commissioner") return <main className="min-h-screen"><Header weekNumber={context.week?.nfl_week}/><section className="mx-auto max-w-xl px-5 pt-16"><h1 className="text-3xl font-black">Commissioner access required</h1></section><BottomNav/></main>;

  const active = context.members.filter((member) => member.status === "active");
  const pending = context.members.filter((member) => member.status === "pending");
  const stats = [[String(active.length), "Active players", Users], [String(context.picks.length), "Picks submitted", ClipboardCheck], [String(pending.length), "Pending members", UserPlus], [context.lastSync ? "Live" : "Waiting", "NFL data", Activity]];

  return <main className="mx-auto min-h-screen max-w-5xl pb-24"><Header weekNumber={context.week?.nfl_week}/><section className="px-5 pt-6">
    <Pill className="border-[hsl(var(--primary)/.4)] text-[hsl(var(--primary))]">Commissioner area</Pill>
    <h1 className="mt-3 text-3xl font-black">Run Week {context.week?.nfl_week ?? "—"}</h1>
    {params.error && <Card className="mt-5 border-red-500/40 p-4 text-sm text-red-200">{params.error}</Card>}
    {params.imported !== undefined && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Official schedule refreshed: {params.gamesUpdated ?? "0"} game{params.gamesUpdated === "1" ? "" : "s"} imported or updated; {params.oddsLines ?? "0"} provider line{params.oddsLines === "1" ? "" : "s"} prefilled.</Card>}
    {params.syncWarning && <Card className="mt-5 border-amber-400/40 p-4 text-sm text-amber-100">Odds were not fully prefilled: {params.syncWarning} Add any missing line manually, then check the latest <code>provider_syncs</code> row.</Card>}
    {params.assisted && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Assisted pick saved and recorded in the audit trail.</Card>}
    {params.finalized && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Week finalized. Season standings now include every official result.</Card>}
    {params.reset && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm text-[hsl(var(--primary))]">Pool reset. Members were retained; open a new week to start again.</Card>}
    <div className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-4">{stats.map(([value, label, Icon]) => { const Symbol = Icon as typeof Users; return <Card className="p-4" key={label as string}><Symbol className="text-[hsl(var(--primary))]" size={18}/><p className="mt-5 text-2xl font-black">{value as string}</p><p className="text-xs font-bold text-[hsl(var(--muted))]">{label as string}</p></Card>; })}</div>
    <div className="mt-6 grid gap-4 md:grid-cols-2"><InvitationForm poolId={pool.id}/><Card className="p-5"><p className="eyebrow">NFL data</p><p className="mt-2 text-xl font-black text-[hsl(var(--primary))]">{context.lastSync ? "Connected" : "Awaiting sync"}</p><p className="mt-2 text-sm text-[hsl(var(--muted))]">{context.lastSync ? `Last successful sync: ${new Date(context.lastSync).toLocaleString()}` : "Deploy and schedule the Supabase sports-sync function."}</p></Card></div>
    <WeekAndLineTools poolId={pool.id} week={context.week} schedule={context.schedule}/><AssistedPickForm poolId={pool.id} weekId={context.week?.id} members={active} games={context.games}/><ResultsTools poolId={pool.id} week={context.week} games={context.games}/>{pool.role === "commissioner" && <ResetPoolForm poolId={pool.id}/>}<MemberList poolId={pool.id} commissioner={pool.role === "commissioner"} currentUserId={context.userId} members={context.members}/>
  </section><BottomNav/></main>;
}

function WeekAndLineTools({ poolId, week, schedule }: { poolId: string; week: { id: string; nfl_week: number; status: "draft" | "open" | "complete" } | null; schedule: ScheduledGame[] }) {
  return <Card className="mt-6 p-5"><h2 className="font-black">Weeks & lines</h2>
    {!week ? <form action={openWeek} className="mt-4 flex flex-wrap gap-3"><input type="hidden" name="poolId" value={poolId}/><input className="focus-ring min-h-11 w-28 rounded-xl border bg-black/20 px-3 text-sm" name="week" type="number" min="1" max="25" required placeholder="Week"/><Button type="submit">Open & import schedule</Button></form>
      : week.status === "complete" ? <><p className="mt-4 text-sm text-[hsl(var(--primary))]">Week {week.nfl_week} is final. Open the next week to import its schedule and auto-fill available odds.</p><form action={openWeek} className="mt-4 flex flex-wrap gap-3"><input type="hidden" name="poolId" value={poolId}/><input className="focus-ring min-h-11 w-28 rounded-xl border bg-black/20 px-3 text-sm" name="week" type="number" min="1" max="25" required defaultValue={week.nfl_week + 1}/><Button type="submit">Open & import next week</Button></form></> : <><div className="mt-4 flex flex-wrap items-center gap-3"><form action={importSchedule}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="week" value={week.nfl_week}/><Button type="submit">Import / refresh official schedule</Button></form><p className="text-xs text-[hsl(var(--muted))]">Fetches the latest NFL schedule, scores, and available odds for Week {week.nfl_week}.</p></div>{schedule.length ? <><p className="mt-5 text-sm text-[hsl(var(--muted))]">Provider lines are prefilled only when a usable spread is returned. Blank fields need a commissioner line; they are never guessed.</p><div className="mt-4 grid gap-3">{schedule.map((game) => <ScheduledLineForm key={game.id} poolId={poolId} weekId={week.id} game={game}/>)}</div></> : <ManualLineForm poolId={poolId} weekId={week.id}/>}</>}
    {!week && <p className="mt-3 text-xs text-[hsl(var(--muted))]">Opening a week imports the official NFL schedule immediately. The background sync keeps scores and kickoff times current.</p>}
    {week && !schedule.length && <p className="mt-3 text-xs text-[hsl(var(--muted))]">The schedule is still loading or the provider is unavailable. You can add a manual game line as a fallback; it will be preserved from provider updates.</p>}
  </Card>;
}

function ScheduledLineForm({ poolId, weekId, game }: { poolId: string; weekId: string; game: ScheduledGame }) {
  const source = game.lineSource?.replace("balldontlie:", "BALLDONTLIE · ").replace("therundown:", "TheRundown · ");
  return <form action={saveScheduledLine} className="grid items-center gap-3 rounded-xl border border-white/10 bg-black/10 p-3 md:grid-cols-[minmax(0,1fr)_11rem_8rem_auto]"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={weekId}/><input type="hidden" name="gameId" value={game.id}/><div><p className="font-bold">{game.away.name} at {game.home.name}</p><p className="text-xs text-[hsl(var(--muted))]">{formatEastern(game.kickoff)}{source ? ` · ${game.lineManuallyOverridden ? "Edited" : source}` : ""}</p></div><select name="underdogTeamId" defaultValue={game.underdogTeamId ?? ""} required className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm"><option value="" disabled>Choose underdog</option><option value={game.away.id}>{game.away.abbreviation} — {game.away.name}</option><option value={game.home.id}>{game.home.abbreviation} — {game.home.name}</option></select><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="spread" defaultValue={game.spread ?? undefined} required type="number" min="0.5" step="0.5" placeholder="Spread"/><Button type="submit" className={game.hasLine ? "bg-white/10 text-white" : undefined}>{game.hasLine ? "Save edit" : "Add line"}</Button></form>;
}

function ManualLineForm({ poolId, weekId }: { poolId: string; weekId: string }) { return <form action={saveManualLine} className="mt-4 grid gap-3 md:grid-cols-5"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={weekId}/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="away" required maxLength={3} placeholder="Away (NYJ)"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="home" required maxLength={3} placeholder="Home (BUF)"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="underdog" required maxLength={3} placeholder="Underdog"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="spread" required type="number" min="0.5" step="0.5" placeholder="Spread"/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm md:col-span-2" name="kickoff" required type="datetime-local"/><Button type="submit">Add game line</Button></form>; }

function AssistedPickForm({ poolId, weekId, members, games }: { poolId: string; weekId: string | undefined; members: PoolMember[]; games: LiveGame[] }) { const options=games.filter((game)=>game.available); return <Card className="mt-6 p-5"><h2 className="font-black">Add or update a player&apos;s pick</h2><p className="mt-1 text-sm text-[hsl(var(--muted))]">Commissioners and co-commissioners can enter or update an active player&apos;s pick before that game&apos;s deadline. Every assisted pick is audited.</p>{weekId && options.length ? <form action={submitAssistedPick} className="mt-4 grid gap-3 md:grid-cols-[minmax(0,1fr)_minmax(0,1.4fr)_auto]"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={weekId}/><select name="playerId" required className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm"><option value="" disabled>Select player</option>{members.map((member)=><option key={member.userId} value={member.userId}>{member.displayName}</option>)}</select><select name="selection" required className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm"><option value="" disabled>Select underdog</option>{options.map((game)=><option key={game.id} value={`${game.id}|${game.underdog.id}`}>{game.underdog.abbreviation} +{game.spread} vs {game.favorite.abbreviation} · {formatEastern(game.kickoff)}</option>)}</select><Button type="submit">Save player pick</Button></form> : <p className="mt-4 text-sm text-[hsl(var(--muted))]">No currently eligible games are available for a player pick.</p>}</Card>; }

function ResultsTools({ poolId, week, games }: { poolId: string; week: { id: string; nfl_week: number; status: "draft" | "open" | "complete" } | null; games: LiveGame[] }) { if(!week) return null; return <Card className="mt-6 p-5"><h2 className="font-black">Results & week close</h2><p className="mt-1 text-sm text-[hsl(var(--muted))]">Provider-scored games finalize automatically. Use a manual score only for a correction or a manually entered fallback game.</p><div className="mt-4 grid gap-3">{games.filter((game)=>game.status!=="final").map((game)=><form key={game.id} action={recordManualResult} className="grid items-center gap-3 rounded-xl border border-white/10 bg-black/10 p-3 md:grid-cols-[minmax(0,1fr)_6rem_6rem_auto]"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="gameId" value={game.id}/><p className="font-bold">{game.away.abbreviation} at {game.home.abbreviation}</p><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="awayScore" required min="0" type="number" placeholder={`${game.away.abbreviation}`}/><input className="focus-ring min-h-11 rounded-xl border bg-black/20 px-3 text-sm" name="homeScore" required min="0" type="number" placeholder={`${game.home.abbreviation}`}/><Button type="submit" className="bg-white/10 text-white">Record result</Button></form>)}</div>{week.status !== "complete" ? <form action={finalizeWeek} className="mt-5"><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="weekId" value={week.id}/><Button type="submit">Finalize Week {week.nfl_week}</Button></form> : <p className="mt-5 text-sm font-bold text-[hsl(var(--primary))]">Week {week.nfl_week} is finalized.</p>}</Card>; }

function MemberList({ poolId, commissioner, currentUserId, members }: { poolId: string; commissioner: boolean; currentUserId: string; members: Array<{ userId: string; displayName: string; status: string; role: "player" | "co_commissioner" | "commissioner" }> }) { return <Card className="mt-6 overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="font-black">Members</h2></div>{members.map((member) => <div className="flex flex-wrap items-center gap-3 border-b border-white/5 p-4 last:border-0" key={member.userId}><div className="min-w-36 flex-1"><p className="font-bold">{member.displayName}</p><p className="text-xs text-[hsl(var(--muted))]">{member.status} · {member.role.replace("_", " ")}</p></div>{member.status === "pending" && commissioner && <><form action={moderateMember}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="userId" value={member.userId}/><input type="hidden" name="status" value="active"/><Button type="submit">Approve</Button></form><form action={moderateMember}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="userId" value={member.userId}/><input type="hidden" name="status" value="rejected"/><Button type="submit" className="bg-white/10 text-white">Reject</Button></form></>}{member.status === "active" && member.userId !== currentUserId && commissioner && <form action={changeMemberRole}><input type="hidden" name="poolId" value={poolId}/><input type="hidden" name="userId" value={member.userId}/><input type="hidden" name="role" value={member.role === "co_commissioner" ? "player" : "co_commissioner"}/><Button type="submit" className="bg-white/10 text-white">{member.role === "co_commissioner" ? "Remove co-commissioner" : "Make co-commissioner"}</Button></form>}</div>)}</Card>; }
