import { LockKeyhole, Radio } from "lucide-react";
import { BottomNav, Header } from "@/components/navigation";
import { Onboarding } from "@/components/onboarding";
import { Card, Pill } from "@/components/ui";
import { requirePoolContext } from "@/lib/data/pool";
import { formatEastern } from "@/lib/domain/deadlines";
import { LiveRefresh } from "@/components/live-refresh";

export default async function PicksPage() { const context=await requirePoolContext(); if(!context.pool || !context.week) return <main className="min-h-screen"><Header/><Onboarding pending={context.pendingPool}/><BottomNav/></main>; const revealed=context.picks.filter((pick)=>context.games.find((game)=>game.id===pick.gameId)?.revealed || pick.playerId===context.userId); const allRevealed=context.games.length>0 && context.games.every((game)=>game.revealed); return <main className="mx-auto min-h-screen max-w-5xl pb-24"><Header/><section className="px-5 pt-6"><p className="eyebrow">{context.pool.name} · Week {context.week.nfl_week}</p><h1 className="mt-2 text-3xl font-black">Pool picks</h1><div className="mt-3"><LiveRefresh/></div>{!allRevealed && <Card className="mt-6 p-5"><div className="flex items-start gap-3"><LockKeyhole className="mt-0.5 text-[hsl(var(--warning))]"/><div><h2 className="font-black">Picks are still revealing</h2><p className="mt-1 text-sm leading-6 text-[hsl(var(--muted))]">Only your selection and picks whose games have started are visible.</p></div></div></Card>}<div className="mt-5 grid gap-3 md:grid-cols-2">{revealed.map((pick)=>{const game=context.games.find((item)=>item.id===pick.gameId); if(!game) return null; const selected=game.underdog; const projected=game.status==="in_progress" && game.awayScore !== null && game.homeScore !== null && ((selected.id===game.away.id ? game.awayScore : game.homeScore) > (selected.id===game.away.id ? game.homeScore : game.awayScore)); return <Card key={pick.id} className="p-4"><div className="flex items-center justify-between"><p className="font-black">{pick.playerName}</p><Pill className="text-[hsl(var(--primary))]">{pick.playerId===context.userId ? "You" : game.status.replace("_"," ")}</Pill></div><p className="mt-4 text-xl font-black">{selected.city} {selected.name} <span className="text-[hsl(var(--primary))]">+{pick.spread}</span></p><p className="mt-1 text-sm text-[hsl(var(--muted))]">vs {game.favorite.city} {game.favorite.name} · {formatEastern(game.kickoff)}</p>{game.awayScore !== null && <p className="mt-4 text-sm font-black">{game.away.abbreviation} {game.awayScore} — {game.home.abbreviation} {game.homeScore}</p>}<p className="mt-3 text-xs font-bold uppercase tracking-wide text-[hsl(var(--muted))]">{game.status === "final" ? `Official ${pick.finalPoints ?? 0} points` : projected ? `Projected +${pick.spread}` : game.status === "in_progress" ? "Projected 0" : "Awaiting kickoff"}</p></Card>})}</div>{revealed.length===0 && <Card className="mt-6 p-6 text-center"><Radio className="mx-auto text-[hsl(var(--primary))]"/><p className="mt-3 font-bold">No revealed selections yet.</p></Card>}</section><BottomNav/></main>; }
