import Link from "next/link";
import { Search, ShieldCheck, UserRound } from "lucide-react";
import { beginDeveloperImpersonation } from "@/app/developer/actions";
import { Button, Card, Pill } from "@/components/ui";
import { developerDirectory, requireDeveloperAccess } from "@/lib/data/developer";

type DeveloperParams = { q?: string; error?: string; sessionEnded?: string };

export default async function DeveloperPage({ searchParams }: { searchParams: Promise<DeveloperParams> }) {
  const params = await searchParams;
  const { user } = await requireDeveloperAccess();
  const accounts = await developerDirectory(params.q);

  return <main className="mx-auto min-h-screen max-w-5xl px-5 pb-16 pt-6"><Link className="focus-ring text-xl font-black" href="/">GAME<span className="text-[hsl(var(--primary))]">DAY</span></Link><section className="mt-8"><Pill className="border-amber-400/40 text-amber-200">Developer support</Pill><h1 className="mt-3 text-3xl font-black">Account support center</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[hsl(var(--muted))]">Review account and pool state, then open a time-limited, read-only support session. Support sessions cannot submit picks, edit pools, or change account data.</p>{params.error && <Card className="mt-5 border-red-500/40 p-4 text-sm text-red-200">{params.error}</Card>}{params.sessionEnded && <Card className="mt-5 border-[hsl(var(--primary)/.4)] p-4 text-sm font-bold text-[hsl(var(--primary))]">Support session ended.</Card>}</section><Card className="mt-6 p-4"><form className="flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="account-search">Search accounts</label><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[hsl(var(--muted))]" size={17}/><input className="focus-ring min-h-11 w-full rounded-xl border bg-black/20 pl-10 pr-3 text-sm" defaultValue={params.q} id="account-search" name="q" placeholder="Search by name or email"/></div><Button type="submit">Search</Button></form></Card><section className="mt-4 grid gap-3">{accounts.map((account) => <Card className="p-4" key={account.user_id}><div className="flex flex-wrap items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[hsl(var(--primary)/.12)] text-[hsl(var(--primary))]"><UserRound size={19}/></span><div className="min-w-0 flex-1"><p className="truncate font-black">{account.display_name}</p><p className="truncate text-sm text-[hsl(var(--muted))]">{account.email ?? "No email available"}</p><p className="mt-1 text-xs text-[hsl(var(--muted))]">{account.pool_count} pool{account.pool_count === 1 ? "" : "s"} · Last sign-in {account.last_sign_in_at ? new Date(account.last_sign_in_at).toLocaleDateString() : "never"}</p></div>{account.user_id === user.id ? <Pill className="border-white/10 text-[hsl(var(--muted))]">Your account</Pill> : <form action={beginDeveloperImpersonation}><input name="targetUserId" type="hidden" value={account.user_id}/><Button className="bg-white/10 text-white hover:bg-white/15" type="submit"><ShieldCheck className="mr-2" size={16}/>View as</Button></form>}</div></Card>)}{!accounts.length && <Card className="p-6 text-sm text-[hsl(var(--muted))]">No matching accounts.</Card>}</section></main>;
}
